[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
prefect-docker = "*"
python = "<3.13"
tiled-client = ">=0.2.1"
databroker = "*"
gcc = "*"  # mass in ucal-autoprocess requires this
