[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
prefect-docker = "*"
python = "<3.14"
tiled-client = ">=0.2.1"
databroker = "*"
gcc = "*"  # mass in ucal-autoprocess requires this

[pypi-dependencies]
ucal-autoprocess = { git = "https://github.com/NSLS-II-SST/ucal-autoprocess.git", branch ="pixi-fix" }
mass = { git = "https://github.com/JunAishima/mass.git", branch="fix-build" }
